version: "3.0"
services:
  broker1:
    image: mosq2
    volumes:
      - ./data1:/mosquitto/data
      - ./log1:/mosquitto/log
    container_name: broker1
    networks:
            - mqtt-broker-net
    tty: true
  broker2:
    image: mosq2
    volumes:
      - ./data2:/mosquitto/data
      - ./log2:/mosquitto/log
    container_name: broker2
    networks:
            - mqtt-broker-net
    tty: true
  broker3:
    image: mosq2
    volumes:
      - ./data3:/mosquitto/data
      - ./log3:/mosquitto/log
    container_name: broker3
    networks:
      - mqtt-broker-net
    tty: true

networks:
        mqtt-broker-net:
                driver: bridge
