version: "3.0"
services:
  publisher:
    image: mosq
    volumes:
      - ./data_cli_pub:/mosquitto/data
      - ./log_cli_pub:/mosquitto/log
    networks:
      - my-net
    tty: true
  subscriber:
    image: mosq
    volumes:
      - ./data_cli_sub:/mosquitto/data
      - ./log_cli_sub:/mosquitto/log
    networks:
      - my-net
    tty: true

networks:
        my-net:
                driver: bridge
