version: "3.0"
services:
  pub:
    image: my_mosq_client
    volumes:
      - ./data_cli_pub:/mosquitto/data
      - ./log_cli_pub:/mosquitto/log
    tty: true
  sub:
    image: my_mosq_client
    volumes:
      - ./data_cli_sub:/mosquitto/data
      - ./log_cli_sub:/mosquitto/log
    tty: true

networks:
        default:
                external:
                        name: my-net
