version: "3.0"
services:
  pub:
    image: my_mosq_client
    volumes:
            - ./data_cli_pub:/client/data
            - ./log_cli_pub:/client/log
    tty: true
  sub:
    image: my_mosq_client
    volumes:
            - ./data_cli_sub:/client/data
            - ./log_cli_sub:/client/log
    tty: true

networks:
        default:
                external:
                        name: my-net
