version: "3.0"
services:
  broker:
    image: my_mosq
    volumes:
      - ./data1:/mosquitto/data
      - ./log1:/mosquitto/log
  # container_name: sub_b1
    networks:
            - my-net
    tty: true

networks:
        my-net:
                driver: bridge
